name: Profile Summary Cards

on:
  schedule:
    - cron: '0 0 * * *'  # every day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: mikecabral
          TOKEN: ${{ secrets.GH_TOKEN }}
          UTC_OFFSET: -4

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile-summary-card-output
          git diff --cached --quiet || git commit -m "Update GitHub profile summary cards"
          git push
